### ISSUE TITLE
No module named 'openai' error

### ISSUE THREAD

**Issue by getsean** [techleadhd/chatgpt-retrieval#19]
![image](https://github.com/techleadhd/chatgpt-retrieval/assets/77656279/77de620d-15e4-44d5-849d-84dc9a13f99b)

Can someone point me in the right direction on fixing this error?

**Comment by getsean** [comment]
Do I need to put these files inside the site-packages/openai folder? I tried and now I get a punch more errors..

**Comment by getsean** [comment]
Fixed the above but now I get

![image](https://github.com/techleadhd/chatgpt-retrieval/assets/77656279/87718b46-1594-4c6b-b222-e8007b80b123)

**Comment by StrictLine** [comment]
Actually, a `requirements.txt` would have been nice to include, but there are not much installation to do:
```zsh
pip install openai
pip install chromadb
pip install 'langchain'
```

Note: I'm not sure at the moment the extension of langchain like `langchain[llms]` or `langchain[all]` needs to be installed.

As for the latest screenshot you posted: it's what it says :) Unfortunately, I stumbled upon this issue, because I thought OpenAI would honor my loyalty of monthly subscription for the ChatGPT, but NO: your free rate limit expires after a while, then you either have a reserve account or choose a paid plan.

**Comment by getsean** [comment]
Thanks. I was able to get it working. I think my billing just took a few minutes to go through after I put my card in because then the rate limit went away for small tests. But if you put like 10 pages of data you will him limits I think.
